services:
  - type: web
    name: foodsuite-pro
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: memory
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_TENANT_ID
        value: demo
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
