services:
  - type: web
    name: foodsuite
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_TENANT_ID
        value: demo
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
      - key: DATABASE_URL
        fromDatabase:
          name: foodsuite-db
          property: connectionString

  - type: pserv
    name: foodsuite-db
    plan: free
    databaseName: foodsuite
    user: foodsuite
    ipAllowList: []
